local syntax = require("matchparen.syntax")

describe("skip_by_region", function()
   vim.cmd.edit("tests/example.lua")
   vim.treesitter.stop()

   it("should return correct function when cursor is on string or comment", function()
      assert.is_false(syntax.skip_by_region(2, 30)(2, 30))
      assert.is_false(syntax.skip_by_region(4, 14)(4, 14))
      assert.is_true(syntax.skip_by_region(2, 30)(5, 4))
      assert.is_true(syntax.skip_by_region(4, 14)(5, 4))
   end)
   it("should return correct function when cursor is not on string or comment", function()
      assert.is_false(syntax.skip_by_region(2, 10)(2, 10))
      assert.is_false(syntax.skip_by_region(5, 4)(5, 4))
      assert.is_true(syntax.skip_by_region(2, 10)(4, 14))
      assert.is_true(syntax.skip_by_region(2, 10)(2, 30))
   end)
   it("should return nil if syntax option is empty", function()
      vim.cmd("set syntax=")
      assert.is_false(syntax.skip_by_region(2, 30)(2, 30))
      vim.cmd("set syntax=lua")
   end)
   it("should return nil if syntax is off", function()
      vim.cmd("syntax off")
      assert.is_false(syntax.skip_by_region(2, 30)(2, 30))
      vim.cmd("syntax on")
   end)

   vim.cmd("bw!")
end)
